- name: "Docker Cadvisor: Setup cadvisor"
  docker_container:
    name: monitor-cadvisor
    image: google/cadvisor
    pull: true
    network_mode: host
    command: "--port=9080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart_policy: on-failure
