---
- hosts: all
  tasks:

  - name: "System: Setup docker repository key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "System: Install pip package"
    apt:
      name: python-setuptools
      state: present
      update_cache: yes

  - name: "System: Install docker-py pip package"
    easy_install:
      name: docker-py

  - name: Update /etc/hosts from inventory
    lineinfile: dest=/etc/hosts regexp='.*{{item}}$' line='{{hostvars[item].ansible_default_ipv4.address}} {{item}}' state=present
    with_items: '{{ groups.all }}'
    tags:
      - hosts

  - name: Update /etc/hosts from string
    lineinfile: dest=/etc/hosts line='{{hostvars[item].ansible_default_ipv4.address}} express42' state=present
    with_items: '{{ groups.all }}'
    tags:
      - hosts
