---
molecule:
  molecule_dir: environments/molecule
  test:
    sequence:
      - destroy
      - create
      - converge
      - destroy
  vagrantfile_template: vagrantfile.j2
ansible:
    config_file: ansible.cfg
    playbook: site.yml
    verbose: false
    host_vars:
      node1:
        mesos_node_master: true
        mesos_node_slave: true
        journal_node_active: true
        journal_node_standby: false
        monitor: true
        prometheus_file_sd_config_path: "/etc/prometheus/sd_files"
      node2:
        mesos_node_master: false
        mesos_node_slave: true
        journal_node_active: false
        journal_node_standby: true
      node3:
        mesos_node_master: false
        mesos_node_slave: true
        journal_node_active: false
        journal_node_standby: false
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"
  platforms:
    - name: xenial64
      box: express42/ubuntu-16.04

  providers:
    - name: parallels
      type: parallels
      options:
        memory: 1024
        cpus: 2

  instances:
    - name: node1
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: no

    - name: node2
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: no

    - name: node3
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
      options:
        append_platform_to_hostname: no
